# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


###################################################
# General
###################################################

# Inserts a blank line between shell prompts
add_newline = true
# Timeout for starship to scan files (in milliseconds)
scan_timeout = 30
# Timeout for commands executed by starship (in milliseconds)
command_timeout = 500


###################################################
# UI
###################################################

format = "$all$username$character"
right_format = """
$aws\
$kubernetes"""
# A continuation prompt that displays two filled in arrows
continuation_prompt = "[∙](bright-black) "


###################################################
# Modules: Basic
###################################################

[character]
success_symbol = "[❯](bold green)"

[directory]
disabled = false
# Use the OS specific path separator instead of always using / (e.g. \ on Windows)
use_os_path_sep = true
# The number of characters to use when applying fish shell pwd path logic
fish_style_pwd_dir_length = 1
# The symbol indicating home directory.
home_symbol = "~"
# The symbol to prefix to truncated paths. eg: '…/'
truncation_symbol = ".../"
# The number of parent folders that the current directory should be truncated to
truncation_length = 2
# Whether or not to truncate to the root of the git repo that you're currently in
truncate_to_repo = false
# The style for the path segment above the root of the git repo. The default value is equivalent to `style`
before_repo_root_style = "bold italic 245"
# The style for the root of the git repo. The default value is equivalent to `style`
repo_root_style = "bold underline 34"
# The format of a git repo when `before_repo_root_style` and `repo_root_style` is defined
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
read_only = " 󰌾"
read_only_style = "red"
style = "bold 34"
format = "[$path]($style)[$read_only]($read_only_style) "

[hostname]
ssh_symbol = " "

[sudo]
disabled = true

[username]
disabled = false
show_always = true
style_user = "bold white"
style_root = "bold underline red"
format = "[$user]($style) "


###################################################
# Modules: VCS
###################################################

[git_branch]
symbol = " "

[hg_branch]
symbol = " "


###################################################
# Modules: Main Tools
###################################################

[aws]
disabled = false
symbol = " "
style = "bold 208"
format = ' [$symbol($profile )(\($region\))]($style)'

[aws.region_aliases]
us-east-1 = "use1"
us-east-2 = "use2"
us-west-1 = "usw1"
us-west-2 = "usw2"
af-south-1 = "afs1"
ap-east-1 = "ape1"
ap-northeast-1 = "apne1"
ap-northeast-2 = "apne2"
ap-northeast-3 = "apne3"
ap-southeast-1 = "apse1"
ap-southeast-2 = "apse2"
ap-southeast-3 = "apse3"
ap-south-1 = "aps1"
ca-central-1 = "cac1"
eu-central-1 = "euc1"
eu-west-1 = "euw1"
eu-west-2 = "euw2"
eu-west-3 = "euw3"
eu-north-1 = "eun1"
eu-south-1 = "eus1"
me-south-1 = "mes1"
sa-east-1 = "sae1"
cn-north-1 = "cn1"
us-gov-west-1 = "usgw1"
us-gov-east-1 = "usge1"

# [aws.profile_aliases]
# CompanyGroupFrobozzOnCallAccess = 'Frobozz'

[docker_context]
symbol = " "

[kubernetes]
disabled = false
detect_files = ["kustomization.yaml", "kustomization.yml", "values.yaml", "values.yml"]
detect_folders = ["k8s", ".k8s", "kubernetes"]
symbol = "󱃾 "
style = "bold 63"
format = ' [$symbol$context]($style)'

[terraform]
disabled = false
detect_extensions = ["tf", "tfplan", "tfstate"]
detect_files = ["terraform.tfstate", ".terraform-version"]
detect_folders = [".terraform"]
symbol = "󱁢 "
style = "bold 105"
version_format = 'v${raw}'
format = 'via [$symbol$workspace]($style) '


###################################################
# Modules: Main Languages
###################################################

[golang]
disabled = false
symbol = " "

[nodejs]
disabled = false
symbol = " "

[php]
disabled = false

[python]
disabled = false
symbol = " "

[ruby]
disabled = false
symbol = " "

[rust]
disabled = false
symbol = " "

[java]
disabled = false
symbol = " "

[scala]
disabled = false
symbol = " "

[swift]
disabled = true



###################################################
# Modules: MISC
###################################################

[package]
disabled = false
symbol = "󰏗 "

[shell]
disabled = true

[shlvl]
disabled = true

[status]
disabled = true

[time]
disabled = true

[vagrant]
disabled = false


###################################################
# Modules: Disabled
###################################################

[battery]
disabled = true

[buf]
disabled = true
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[perl]
disabled = true

[pijul_channel]
symbol = " "

[purescript]
disabled = true

[rlang]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[singularity]
disabled = true

[solidity]
disabled = true

[spack]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true
