[tools]
node = "26"
ruby = "4.0.5"
terraform = "latest"

[tool_alias]
terraform = "asdf:mise-plugins/mise-hashicorp"

[settings]
idiomatic_version_file_enable_tools = ["deno", "node", "terraform", "packer"]
