[tools]
terraform = "latest"

[tool_alias]
terraform = "asdf:asdf-community/asdf-hashicorp"

[settings]
idiomatic_version_file_enable_tools = ["terraform"]


# "_" is a special key for information you'd like to put into mise.toml that mise will never parse
[_]
foo = "bar"
