[ui]
mouse_capture = true


[keys]
# Prefix
prefix = "ctrl+a"

# Session
detach = "prefix+d"
reload_config = "prefix+shift+r"

# Tabs
new_tab = "prefix+c"
switch_tab = "prefix+1..9"
next_tab = ["prefix+n", "prefix+right"]
previous_tab = ["prefix+p", "prefix+left"]

# Panes
focus_pane_left = "prefix+h"
focus_pane_down = "prefix+j"
focus_pane_up = "prefix+k"
focus_pane_right = "prefix+l"
split_horizontal = "prefix+minus"
split_vertical = "prefix+|"
