[ui]
mouse_capture = true


[ui.toast]
delivery = "herdr"


[theme]
name = "terminal"
auto_switch = false


[keys]
# Prefix
prefix = "ctrl+a"

# Session
detach = "prefix+d"
reload_config = "prefix+shift+r"

# Workspaces
workspace_picker = "prefix+w"
switch_workspace = "prefix+shift+1..9"
previous_workspace = "prefix+up"
next_workspace = "prefix+down"

# Tabs
new_tab = "prefix+c"
switch_tab = "prefix+1..9"
next_tab = ["prefix+n", "prefix+right"]
previous_tab = ["prefix+p", "prefix+left"]

# Panes
focus_pane_left = ["prefix+h", "alt+h"]
focus_pane_down = ["prefix+j", "alt+j"]
focus_pane_up = ["prefix+k", "alt+k"]
focus_pane_right = ["prefix+l", "alt+l"]
split_horizontal = "prefix+minus"
split_vertical = "prefix+|"
